### ISSUE TITLE
arzon.jp scraper not working

### ISSUE THREAD

**Issue by dearestk** [laoyang945/javscraper#10]
There seems to be a change in arzon.jp website hence the scraper for it is not working. Appreciate if this could be remedied. And thank you very much for your work.

**Comment by samfriend** [comment]
same here, thank you for your work

**Comment by centalinetht** [comment]
you scraper is always the best! A lot of people are supporting you! You're not alone!

**Comment by laoyang945** [comment]
will fix this weekend

**Comment by SwedishGojira** [comment]
How is it going? Hoping this is fixed soon because this is my most used scraper ;)

**Comment by SwedishGojira** [comment]
Managed to hack a solution by myself by scraping arzon.jp directly and skipping your scripts on herokuapp. I have no source to those scripts so I have no idea what they are doing, but I suspect you need to change them to use https like I did with everything else.
First time doing this and I'm no coder, but it seems to work for now. Hopefully you can use my fork as an entry point to speed things up when you fix it officially.

**Comment by SwedishGojira** [comment]
If you can't wait for laoyang945 to update you can always get my fixed fork here: https://github.com/SwedishGojira/javscraper

**Comment by dearestk** [comment]
using SwedishGojira amended fork without any problem. thanks bro.

**Comment by laoyang945** [comment]
Thanks! SwedishGojira, busy this month so no time to fix this. for arzon, I think it's ok to just herokuapp because it's utf-8 encoded. The heroku proxy is only for non utf-8 encoding to utf-8 encoding.
