### ISSUE TITLE
Server Connection Problem

### ISSUE THREAD

**Issue by centalinetht** [laoyang945/javscraper#9]
Seems the site included in XML file before connecting to DMM is not valid. Is it anyways to fix it? like pointing to other site for XBMC? or you have changed to use another site for this service?

Use tell how important your scraper is, coz other scrapers make English Title, and the data you scraper is better for Asian users! :)

**Comment by jakiesun** [comment]
It always says that it cannot connect. I didn't changed anything about the xml. I am very appreciated your work about the scraper. Thank you!

**Comment by laoyang945** [comment]
fixed, please update to the latest scraper
